/**
 * Writes content/examples.ts from public/engine/ex/*.json — which examples each
 * product page offers, in id order, with their tab names.  npx tsx tools/showcase/manifest.ts
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
const dir = "public/engine/ex";
const by: Record<string, { id: string; tab: string; url: string }[]> = {};
for (const f of readdirSync(dir).filter((x) => x.endsWith(".json")).sort()) {
  const j = JSON.parse(readFileSync(`${dir}/${f}`, "utf8"));
  (by[j.slug] ??= []).push({ id: j.id, tab: j.tab, url: `/engine/ex/${f}` });
}
for (const k of Object.keys(by)) by[k].sort((a, b) => a.id.localeCompare(b.id));
writeFileSync("content/examples.ts", `// GENERATED by tools/showcase/manifest.ts from public/engine/ex — do not edit by hand.\nimport type { ExampleRef } from "@/components/engine/Engine";\n\nexport const EXAMPLES: Record<string, ExampleRef[]> = ${JSON.stringify(by, null, 2)};\n`);
console.log(Object.entries(by).map(([k, v]) => `${k}: ${v.length}`).join("  "));
