// GENERATED by tools/showcase/manifest.ts from public/engine/ex — do not edit by hand.
import type { ExampleRef } from "@/components/engine/Engine";

export const EXAMPLES: Record<string, ExampleRef[]> = {
  "adaptive-priceline": [
    {
      "id": "a",
      "tab": "On the candle",
      "url": "/engine/ex/adaptive-priceline-a.json"
    },
    {
      "id": "b",
      "tab": "Stepping down",
      "url": "/engine/ex/adaptive-priceline-b.json"
    }
  ],
  "asl": [
    {
      "id": "a",
      "tab": "Up from value",
      "url": "/engine/ex/asl-a.json"
    },
    {
      "id": "b",
      "tab": "Down from value",
      "url": "/engine/ex/asl-b.json"
    }
  ],
  "chart-price": [
    {
      "id": "a",
      "tab": "Selling, then a stall",
      "url": "/engine/ex/chart-price-a.json"
    },
    {
      "id": "b",
      "tab": "Buying, then a stall",
      "url": "/engine/ex/chart-price-b.json"
    }
  ],
  "ds-258": [
    {
      "id": "a",
      "tab": "Up the map",
      "url": "/engine/ex/ds-258-a.json"
    },
    {
      "id": "b",
      "tab": "Down the map",
      "url": "/engine/ex/ds-258-b.json"
    }
  ],
  "flow": [
    {
      "id": "a",
      "tab": "Sweep low",
      "url": "/engine/ex/flow-a.json"
    },
    {
      "id": "b",
      "tab": "Sweep high",
      "url": "/engine/ex/flow-b.json"
    }
  ],
  "gex": [
    {
      "id": "a",
      "tab": "Call Wall caps",
      "url": "/engine/ex/gex-a.json"
    },
    {
      "id": "b",
      "tab": "Put Wall holds",
      "url": "/engine/ex/gex-b.json"
    }
  ],
  "iceberg": [
    {
      "id": "a",
      "tab": "ICE BID",
      "url": "/engine/ex/iceberg-a.json"
    },
    {
      "id": "b",
      "tab": "ICE OFFER",
      "url": "/engine/ex/iceberg-b.json"
    }
  ],
  "macd": [
    {
      "id": "a",
      "tab": "Bull setup",
      "url": "/engine/ex/macd-a.json"
    },
    {
      "id": "b",
      "tab": "Bear setup",
      "url": "/engine/ex/macd-b.json"
    }
  ],
  "oracle": [
    {
      "id": "a",
      "tab": "Bullish turn",
      "url": "/engine/ex/oracle-a.json"
    },
    {
      "id": "b",
      "tab": "Bearish turn",
      "url": "/engine/ex/oracle-b.json"
    }
  ],
  "parallax": [
    {
      "id": "a",
      "tab": "Buy-side sweep",
      "url": "/engine/ex/parallax-a.json"
    },
    {
      "id": "b",
      "tab": "Sell-side sweep",
      "url": "/engine/ex/parallax-b.json"
    }
  ],
  "proheikinashi": [
    {
      "id": "a",
      "tab": "The turn up",
      "url": "/engine/ex/proheikinashi-a.json"
    },
    {
      "id": "b",
      "tab": "The turn down",
      "url": "/engine/ex/proheikinashi-b.json"
    }
  ],
  "proliquidityhunter": [
    {
      "id": "a",
      "tab": "Swept high",
      "url": "/engine/ex/proliquidityhunter-a.json"
    },
    {
      "id": "b",
      "tab": "Low run",
      "url": "/engine/ex/proliquidityhunter-b.json"
    }
  ],
  "prorsi": [
    {
      "id": "a",
      "tab": "Support",
      "url": "/engine/ex/prorsi-a.json"
    },
    {
      "id": "b",
      "tab": "Resistance",
      "url": "/engine/ex/prorsi-b.json"
    }
  ],
  "protrendrange": [
    {
      "id": "a",
      "tab": "Trend, pullback, resume",
      "url": "/engine/ex/protrendrange-a.json"
    },
    {
      "id": "b",
      "tab": "Range, then trend",
      "url": "/engine/ex/protrendrange-b.json"
    }
  ],
  "session-levels": [
    {
      "id": "a",
      "tab": "Highs taken",
      "url": "/engine/ex/session-levels-a.json"
    },
    {
      "id": "b",
      "tab": "Highs hold",
      "url": "/engine/ex/session-levels-b.json"
    }
  ],
  "squeeze": [
    {
      "id": "a",
      "tab": "Fire long",
      "url": "/engine/ex/squeeze-a.json"
    },
    {
      "id": "b",
      "tab": "Reversion",
      "url": "/engine/ex/squeeze-b.json"
    }
  ],
  "stochastics": [
    {
      "id": "a",
      "tab": "Oversold",
      "url": "/engine/ex/stochastics-a.json"
    },
    {
      "id": "b",
      "tab": "Overbought",
      "url": "/engine/ex/stochastics-b.json"
    }
  ],
  "vwap": [
    {
      "id": "a",
      "tab": "Return, then up",
      "url": "/engine/ex/vwap-a.json"
    },
    {
      "id": "b",
      "tab": "Return, then down",
      "url": "/engine/ex/vwap-b.json"
    }
  ],
  "zones": [
    {
      "id": "a",
      "tab": "Zone holds",
      "url": "/engine/ex/zones-a.json"
    },
    {
      "id": "b",
      "tab": "Supply holds",
      "url": "/engine/ex/zones-b.json"
    }
  ]
};
